language: node_js

sudo: false

services:
  - redis-server
  - docker

node_js:
  - '10'
  - '11'
  - '12'
  - 'stable'

install:
  - yarn install
  - docker pull grokzen/redis-cluster:4.0.8
  - docker run -d -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 --name redis-cluster grokzen/redis-cluster:4.0.8

script:
  - yarn run lint
  - yarn run test

after_script:
  - docker stop redis-cluster
  - docker rm redis-cluster

jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
